#### Devices Supported by KangXperiaProject
add_lunch_combo aokp_anzu-userdebug
add_lunch_combo aokp_nozomi-userdebug
add_lunch_combo aokp_haida-userdebug
add_lunch_combo aokp_hikari-userdebug
add_lunch_combo aokp_zeus-userdebug
add_lunch_combo aokp_hallon-userdebug
add_lunch_combo aokp_satsuma-userdebug
add_lunch_combo aokp_urushi-userdebug
add_lunch_combo aokp_smultron-userdebug
add_lunch_combo aokp_coconut-userdebug
add_lunch_combo aokp_mango-userdebug
#add_lunch_combo aokp_iyokan-userdebug
#add_lunch_combo aokp_zeusc-userdebug
#add_lunch_combo aokp_es209ra-userdebug
#add_lunch_combo aokp_shakira-userdebug
#add_lunch_combo aokp_robyn-userdebug
#add_lunch_combo aokp_mimmi-userdebug
