#### Devices Supported by KangXperiaProject
add_lunch_combo aokp_anzu-userdebug
add_lunch_combo aokp_nozomi-userdebug
add_lunch_combo aokp_urushi-userdebug
add_lunch_combo aokp_zeus-userdebug
add_lunch_combo aokp_es209ra-userdebug
add_lunch_combo aokp_shakira-userdebug
add_lunch_combo aokp_robyn-userdebug
add_lunch_combo aokp_mimmi-userdebug
add_lunch_combo aokp_smultron-userdebug
add_lunch_combo aokp_satsuma-userdebug
add_lunch_combo aokp_coconut-userdebug

